added tests
AnacondaRecipes/pycryptodome-feedstock pull request #4
Opened 2021-12-14 22:34 UTC by abolla22

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2021-12-14 23:37 UTC, remkade requested changes
Looks good! Some minor changes.

2021-12-14 23:37 UTC, remkade commented on recipe/run_test.py
> +test_pycrptodome_pkg()
```suggestion
test_pycryptodome_pkg()
```

2021-12-14 23:37 UTC, remkade commented on recipe/run_test.py
> +def test_pycrptodome_pkg():
```suggestion
def test_pycryptodome_pkg():
```

2021-12-14 23:37 UTC, remkade commented on recipe/run_test.py
> +    py>3.8 versions
These comments seem to apply to pycrypto, can you update them for pycryptodome?

2021-12-15 08:34 UTC, skupr-anaconda commented
The license should be `license: BSD-2-Clause`, see https://github.com/Legrandin/pycryptodome/blob/v3.10.1/LICENSE.rst

And in `host`:
- Missing `wheel` package
- Missing `setuptools` package

Also, it would be nice to add in the test section:
```
  commands:
    - pip check
```

2021-12-15 16:38 UTC, skupr-anaconda approved these changes

2021-12-15 20:30 UTC, remkade reviewed
Looks good to me!

2021-12-15 20:30 UTC, remkade approved these changes

2021-12-15 20:39 UTC, merged